//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminAnswer
    {
        public string Id { get; set; }
        public string AnswerText { get; set; }
        public string AdminQuestion_Id { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
    
        public virtual AdminQuestion AdminQuestion { get; set; }
    }
}
