//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condition
    {
        public int Id { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> MaxAge { get; set; }
        public Nullable<int> MinAge { get; set; }
        public Nullable<int> PeopleCount { get; set; }
        public Nullable<decimal> EachPersonMoney { get; set; }
        public Nullable<int> Field_Id { get; set; }
        public Nullable<int> City_Id { get; set; }
        public Nullable<int> Provience_Id { get; set; }
        public string Questionnaire_Id { get; set; }
    
        public virtual City City { get; set; }
        public virtual Province Province { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual StudyField StudyField { get; set; }
    }
}
