//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public string Id { get; set; }
        public string User_Id { get; set; }
        public Nullable<int> SitePercent { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
