//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EX_MultipleChoiceResponses
    {
        public int Id { get; set; }
        public string Answer_Id { get; set; }
        public string User_Id { get; set; }
    
        public virtual EX_MultipleChoiceAnswers EX_MultipleChoiceAnswers { get; set; }
    }
}
