//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyToReferer
    {
        public int Id { get; set; }
        public string Questionnaire_Id { get; set; }
        public string ToUser_Id { get; set; }
        public Nullable<int> PercentToUser { get; set; }
        public Nullable<decimal> MoneyToUser { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
    }
}
