//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnaire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questionnaire()
        {
            this.Conditions = new HashSet<Condition>();
            this.MoneyToReferers = new HashSet<MoneyToReferer>();
            this.QuestionnaireRequests = new HashSet<QuestionnaireRequest>();
            this.Questions = new HashSet<Question>();
            this.Responses = new HashSet<Respons>();
        }
    
        public string Id { get; set; }
        public string User_Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<System.DateTime> DateSpecialExpire { get; set; }
        public Nullable<int> Special_Id { get; set; }
        public Nullable<decimal> EachPersonMoneyPrice { get; set; }
        public Nullable<int> SitePercentValue { get; set; }
        public Nullable<decimal> SitePercentPrice { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> AnsweredByPerson { get; set; }
        public Nullable<decimal> RemainMoney { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string Editor_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Condition> Conditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoneyToReferer> MoneyToReferers { get; set; }
        public virtual QuestionnaireCategory QuestionnaireCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionnaireRequest> QuestionnaireRequests { get; set; }
        public virtual SpecialOffer SpecialOffer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respons> Responses { get; set; }
    }
}
