//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respons()
        {
            this.UsersResponses = new HashSet<UsersRespons>();
        }
    
        public int Id { get; set; }
        public string User_Id { get; set; }
        public string Questionnaire_Id { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<bool> IsBanned { get; set; }
        public Nullable<decimal> ReceivedMoneyAmount { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Questionnaire Questionnaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersRespons> UsersResponses { get; set; }
    }
}
