//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponderReport
    {
        public int id { get; set; }
        public string ResponderID { get; set; }
        public string QuastionarID { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string EditorID { get; set; }
    }
}
