//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionnaireProject.SmsServiceIran {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsServiceIran.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name appcode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroup", ReplyAction="*")]
        QuestionnaireProject.SmsServiceIran.getgroupResponse getgroup(QuestionnaireProject.SmsServiceIran.getgroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroup", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupResponse> getgroupAsync(QuestionnaireProject.SmsServiceIran.getgroupRequest request);
        
        // CODEGEN: Generating message contract since element name appcode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getmobilebulk", ReplyAction="*")]
        QuestionnaireProject.SmsServiceIran.getmobilebulkResponse getmobilebulk(QuestionnaireProject.SmsServiceIran.getmobilebulkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getmobilebulk", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getmobilebulkResponse> getmobilebulkAsync(QuestionnaireProject.SmsServiceIran.getmobilebulkRequest request);
        
        // CODEGEN: Generating message contract since element name appcode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupstr", ReplyAction="*")]
        QuestionnaireProject.SmsServiceIran.getgroupstrResponse getgroupstr(QuestionnaireProject.SmsServiceIran.getgroupstrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupstr", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupstrResponse> getgroupstrAsync(QuestionnaireProject.SmsServiceIran.getgroupstrRequest request);
        
        // CODEGEN: Generating message contract since element name groupid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupmobiles", ReplyAction="*")]
        QuestionnaireProject.SmsServiceIran.getgroupmobilesResponse getgroupmobiles(QuestionnaireProject.SmsServiceIran.getgroupmobilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupmobiles", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupmobilesResponse> getgroupmobilesAsync(QuestionnaireProject.SmsServiceIran.getgroupmobilesRequest request);
        
        // CODEGEN: Generating message contract since element name groupid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupmobilesstr", ReplyAction="*")]
        QuestionnaireProject.SmsServiceIran.getgroupmobilesstrResponse getgroupmobilesstr(QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupmobilesstr", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupmobilesstrResponse> getgroupmobilesstrAsync(QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequest request);
        
        // CODEGEN: Generating message contract since element name groupid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupcount", ReplyAction="*")]
        QuestionnaireProject.SmsServiceIran.getgroupcountResponse getgroupcount(QuestionnaireProject.SmsServiceIran.getgroupcountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getgroupcount", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupcountResponse> getgroupcountAsync(QuestionnaireProject.SmsServiceIran.getgroupcountRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        QuestionnaireProject.SmsServiceIran.SendSMSResponse SendSMS(QuestionnaireProject.SmsServiceIran.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.SendSMSResponse> SendSMSAsync(QuestionnaireProject.SmsServiceIran.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemainSms", ReplyAction="*")]
        QuestionnaireProject.SmsServiceIran.RemainSmsResponse RemainSms(QuestionnaireProject.SmsServiceIran.RemainSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemainSms", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.RemainSmsResponse> RemainSmsAsync(QuestionnaireProject.SmsServiceIran.RemainSmsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send1sms", ReplyAction="*")]
        QuestionnaireProject.SmsServiceIran.Send1smsResponse Send1sms(QuestionnaireProject.SmsServiceIran.Send1smsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send1sms", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.Send1smsResponse> Send1smsAsync(QuestionnaireProject.SmsServiceIran.Send1smsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send1Bulk", ReplyAction="*")]
        QuestionnaireProject.SmsServiceIran.Send1BulkResponse Send1Bulk(QuestionnaireProject.SmsServiceIran.Send1BulkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Send1Bulk", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.Send1BulkResponse> Send1BulkAsync(QuestionnaireProject.SmsServiceIran.Send1BulkRequest request);
        
        // CODEGEN: Generating message contract since element name cityid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getcitymobiles", ReplyAction="*")]
        QuestionnaireProject.SmsServiceIran.getcitymobilesResponse getcitymobiles(QuestionnaireProject.SmsServiceIran.getcitymobilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getcitymobiles", ReplyAction="*")]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getcitymobilesResponse> getcitymobilesAsync(QuestionnaireProject.SmsServiceIran.getcitymobilesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroup", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getgroupRequestBody Body;
        
        public getgroupRequest() {
        }
        
        public getgroupRequest(QuestionnaireProject.SmsServiceIran.getgroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appcode;
        
        public getgroupRequestBody() {
        }
        
        public getgroupRequestBody(string appcode) {
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getgroupResponseBody Body;
        
        public getgroupResponse() {
        }
        
        public getgroupResponse(QuestionnaireProject.SmsServiceIran.getgroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupResult;
        
        public getgroupResponseBody() {
        }
        
        public getgroupResponseBody(string getgroupResult) {
            this.getgroupResult = getgroupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getmobilebulkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmobilebulk", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getmobilebulkRequestBody Body;
        
        public getmobilebulkRequest() {
        }
        
        public getmobilebulkRequest(QuestionnaireProject.SmsServiceIran.getmobilebulkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getmobilebulkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string postcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string citycode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mode;
        
        public getmobilebulkRequestBody() {
        }
        
        public getmobilebulkRequestBody(string appcode, string postcode, string citycode, string mode) {
            this.appcode = appcode;
            this.postcode = postcode;
            this.citycode = citycode;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getmobilebulkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmobilebulkResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getmobilebulkResponseBody Body;
        
        public getmobilebulkResponse() {
        }
        
        public getmobilebulkResponse(QuestionnaireProject.SmsServiceIran.getmobilebulkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getmobilebulkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getmobilebulkResult;
        
        public getmobilebulkResponseBody() {
        }
        
        public getmobilebulkResponseBody(string getmobilebulkResult) {
            this.getmobilebulkResult = getmobilebulkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupstrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupstr", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getgroupstrRequestBody Body;
        
        public getgroupstrRequest() {
        }
        
        public getgroupstrRequest(QuestionnaireProject.SmsServiceIran.getgroupstrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupstrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string appcode;
        
        public getgroupstrRequestBody() {
        }
        
        public getgroupstrRequestBody(string appcode) {
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupstrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupstrResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getgroupstrResponseBody Body;
        
        public getgroupstrResponse() {
        }
        
        public getgroupstrResponse(QuestionnaireProject.SmsServiceIran.getgroupstrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupstrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupstrResult;
        
        public getgroupstrResponseBody() {
        }
        
        public getgroupstrResponseBody(string getgroupstrResult) {
            this.getgroupstrResult = getgroupstrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupmobilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobiles", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getgroupmobilesRequestBody Body;
        
        public getgroupmobilesRequest() {
        }
        
        public getgroupmobilesRequest(QuestionnaireProject.SmsServiceIran.getgroupmobilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupmobilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appcode;
        
        public getgroupmobilesRequestBody() {
        }
        
        public getgroupmobilesRequestBody(string groupid, string appcode) {
            this.groupid = groupid;
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupmobilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getgroupmobilesResponseBody Body;
        
        public getgroupmobilesResponse() {
        }
        
        public getgroupmobilesResponse(QuestionnaireProject.SmsServiceIran.getgroupmobilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupmobilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupmobilesResult;
        
        public getgroupmobilesResponseBody() {
        }
        
        public getgroupmobilesResponseBody(string getgroupmobilesResult) {
            this.getgroupmobilesResult = getgroupmobilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupmobilesstrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobilesstr", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequestBody Body;
        
        public getgroupmobilesstrRequest() {
        }
        
        public getgroupmobilesstrRequest(QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupmobilesstrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appcode;
        
        public getgroupmobilesstrRequestBody() {
        }
        
        public getgroupmobilesstrRequestBody(string groupid, string appcode) {
            this.groupid = groupid;
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupmobilesstrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupmobilesstrResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getgroupmobilesstrResponseBody Body;
        
        public getgroupmobilesstrResponse() {
        }
        
        public getgroupmobilesstrResponse(QuestionnaireProject.SmsServiceIran.getgroupmobilesstrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupmobilesstrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupmobilesstrResult;
        
        public getgroupmobilesstrResponseBody() {
        }
        
        public getgroupmobilesstrResponseBody(string getgroupmobilesstrResult) {
            this.getgroupmobilesstrResult = getgroupmobilesstrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupcountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupcount", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getgroupcountRequestBody Body;
        
        public getgroupcountRequest() {
        }
        
        public getgroupcountRequest(QuestionnaireProject.SmsServiceIran.getgroupcountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupcountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string groupid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string appcode;
        
        public getgroupcountRequestBody() {
        }
        
        public getgroupcountRequestBody(string groupid, string appcode) {
            this.groupid = groupid;
            this.appcode = appcode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getgroupcountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getgroupcountResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getgroupcountResponseBody Body;
        
        public getgroupcountResponse() {
        }
        
        public getgroupcountResponse(QuestionnaireProject.SmsServiceIran.getgroupcountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getgroupcountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getgroupcountResult;
        
        public getgroupcountResponseBody() {
        }
        
        public getgroupcountResponseBody(string getgroupcountResult) {
            this.getgroupcountResult = getgroupcountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(QuestionnaireProject.SmsServiceIran.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobileno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string pnlno;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string username, string password, string text, string mobileno, string pnlno) {
            this.username = username;
            this.password = password;
            this.text = text;
            this.mobileno = mobileno;
            this.pnlno = pnlno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(QuestionnaireProject.SmsServiceIran.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(string SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemainSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemainSms", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.RemainSmsRequestBody Body;
        
        public RemainSmsRequest() {
        }
        
        public RemainSmsRequest(QuestionnaireProject.SmsServiceIran.RemainSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemainSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public RemainSmsRequestBody() {
        }
        
        public RemainSmsRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemainSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemainSmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.RemainSmsResponseBody Body;
        
        public RemainSmsResponse() {
        }
        
        public RemainSmsResponse(QuestionnaireProject.SmsServiceIran.RemainSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemainSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemainSmsResult;
        
        public RemainSmsResponseBody() {
        }
        
        public RemainSmsResponseBody(string RemainSmsResult) {
            this.RemainSmsResult = RemainSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send1smsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1sms", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.Send1smsRequestBody Body;
        
        public Send1smsRequest() {
        }
        
        public Send1smsRequest(QuestionnaireProject.SmsServiceIran.Send1smsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send1smsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobileno;
        
        public Send1smsRequestBody() {
        }
        
        public Send1smsRequestBody(string username, string text, string mobileno) {
            this.username = username;
            this.text = text;
            this.mobileno = mobileno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send1smsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1smsResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.Send1smsResponseBody Body;
        
        public Send1smsResponse() {
        }
        
        public Send1smsResponse(QuestionnaireProject.SmsServiceIran.Send1smsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send1smsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Send1smsResult;
        
        public Send1smsResponseBody() {
        }
        
        public Send1smsResponseBody(string Send1smsResult) {
            this.Send1smsResult = Send1smsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send1BulkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1Bulk", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.Send1BulkRequestBody Body;
        
        public Send1BulkRequest() {
        }
        
        public Send1BulkRequest(QuestionnaireProject.SmsServiceIran.Send1BulkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send1BulkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobileno;
        
        public Send1BulkRequestBody() {
        }
        
        public Send1BulkRequestBody(string username, string text, string mobileno) {
            this.username = username;
            this.text = text;
            this.mobileno = mobileno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Send1BulkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Send1BulkResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.Send1BulkResponseBody Body;
        
        public Send1BulkResponse() {
        }
        
        public Send1BulkResponse(QuestionnaireProject.SmsServiceIran.Send1BulkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Send1BulkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Send1BulkResult;
        
        public Send1BulkResponseBody() {
        }
        
        public Send1BulkResponseBody(string Send1BulkResult) {
            this.Send1BulkResult = Send1BulkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcitymobilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcitymobiles", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getcitymobilesRequestBody Body;
        
        public getcitymobilesRequest() {
        }
        
        public getcitymobilesRequest(QuestionnaireProject.SmsServiceIran.getcitymobilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getcitymobilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cityid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int mode;
        
        public getcitymobilesRequestBody() {
        }
        
        public getcitymobilesRequestBody(string cityid, int mode) {
            this.cityid = cityid;
            this.mode = mode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getcitymobilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getcitymobilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public QuestionnaireProject.SmsServiceIran.getcitymobilesResponseBody Body;
        
        public getcitymobilesResponse() {
        }
        
        public getcitymobilesResponse(QuestionnaireProject.SmsServiceIran.getcitymobilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getcitymobilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getcitymobilesResult;
        
        public getcitymobilesResponseBody() {
        }
        
        public getcitymobilesResponseBody(string getcitymobilesResult) {
            this.getcitymobilesResult = getcitymobilesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : QuestionnaireProject.SmsServiceIran.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<QuestionnaireProject.SmsServiceIran.ServiceSoap>, QuestionnaireProject.SmsServiceIran.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestionnaireProject.SmsServiceIran.getgroupResponse QuestionnaireProject.SmsServiceIran.ServiceSoap.getgroup(QuestionnaireProject.SmsServiceIran.getgroupRequest request) {
            return base.Channel.getgroup(request);
        }
        
        public string getgroup(string appcode) {
            QuestionnaireProject.SmsServiceIran.getgroupRequest inValue = new QuestionnaireProject.SmsServiceIran.getgroupRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getgroupRequestBody();
            inValue.Body.appcode = appcode;
            QuestionnaireProject.SmsServiceIran.getgroupResponse retVal = ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getgroup(inValue);
            return retVal.Body.getgroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupResponse> QuestionnaireProject.SmsServiceIran.ServiceSoap.getgroupAsync(QuestionnaireProject.SmsServiceIran.getgroupRequest request) {
            return base.Channel.getgroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupResponse> getgroupAsync(string appcode) {
            QuestionnaireProject.SmsServiceIran.getgroupRequest inValue = new QuestionnaireProject.SmsServiceIran.getgroupRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getgroupRequestBody();
            inValue.Body.appcode = appcode;
            return ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getgroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestionnaireProject.SmsServiceIran.getmobilebulkResponse QuestionnaireProject.SmsServiceIran.ServiceSoap.getmobilebulk(QuestionnaireProject.SmsServiceIran.getmobilebulkRequest request) {
            return base.Channel.getmobilebulk(request);
        }
        
        public string getmobilebulk(string appcode, string postcode, string citycode, string mode) {
            QuestionnaireProject.SmsServiceIran.getmobilebulkRequest inValue = new QuestionnaireProject.SmsServiceIran.getmobilebulkRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getmobilebulkRequestBody();
            inValue.Body.appcode = appcode;
            inValue.Body.postcode = postcode;
            inValue.Body.citycode = citycode;
            inValue.Body.mode = mode;
            QuestionnaireProject.SmsServiceIran.getmobilebulkResponse retVal = ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getmobilebulk(inValue);
            return retVal.Body.getmobilebulkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getmobilebulkResponse> QuestionnaireProject.SmsServiceIran.ServiceSoap.getmobilebulkAsync(QuestionnaireProject.SmsServiceIran.getmobilebulkRequest request) {
            return base.Channel.getmobilebulkAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getmobilebulkResponse> getmobilebulkAsync(string appcode, string postcode, string citycode, string mode) {
            QuestionnaireProject.SmsServiceIran.getmobilebulkRequest inValue = new QuestionnaireProject.SmsServiceIran.getmobilebulkRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getmobilebulkRequestBody();
            inValue.Body.appcode = appcode;
            inValue.Body.postcode = postcode;
            inValue.Body.citycode = citycode;
            inValue.Body.mode = mode;
            return ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getmobilebulkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestionnaireProject.SmsServiceIran.getgroupstrResponse QuestionnaireProject.SmsServiceIran.ServiceSoap.getgroupstr(QuestionnaireProject.SmsServiceIran.getgroupstrRequest request) {
            return base.Channel.getgroupstr(request);
        }
        
        public string getgroupstr(string appcode) {
            QuestionnaireProject.SmsServiceIran.getgroupstrRequest inValue = new QuestionnaireProject.SmsServiceIran.getgroupstrRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getgroupstrRequestBody();
            inValue.Body.appcode = appcode;
            QuestionnaireProject.SmsServiceIran.getgroupstrResponse retVal = ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getgroupstr(inValue);
            return retVal.Body.getgroupstrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupstrResponse> QuestionnaireProject.SmsServiceIran.ServiceSoap.getgroupstrAsync(QuestionnaireProject.SmsServiceIran.getgroupstrRequest request) {
            return base.Channel.getgroupstrAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupstrResponse> getgroupstrAsync(string appcode) {
            QuestionnaireProject.SmsServiceIran.getgroupstrRequest inValue = new QuestionnaireProject.SmsServiceIran.getgroupstrRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getgroupstrRequestBody();
            inValue.Body.appcode = appcode;
            return ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getgroupstrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestionnaireProject.SmsServiceIran.getgroupmobilesResponse QuestionnaireProject.SmsServiceIran.ServiceSoap.getgroupmobiles(QuestionnaireProject.SmsServiceIran.getgroupmobilesRequest request) {
            return base.Channel.getgroupmobiles(request);
        }
        
        public string getgroupmobiles(string groupid, string appcode) {
            QuestionnaireProject.SmsServiceIran.getgroupmobilesRequest inValue = new QuestionnaireProject.SmsServiceIran.getgroupmobilesRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getgroupmobilesRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            QuestionnaireProject.SmsServiceIran.getgroupmobilesResponse retVal = ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getgroupmobiles(inValue);
            return retVal.Body.getgroupmobilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupmobilesResponse> QuestionnaireProject.SmsServiceIran.ServiceSoap.getgroupmobilesAsync(QuestionnaireProject.SmsServiceIran.getgroupmobilesRequest request) {
            return base.Channel.getgroupmobilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupmobilesResponse> getgroupmobilesAsync(string groupid, string appcode) {
            QuestionnaireProject.SmsServiceIran.getgroupmobilesRequest inValue = new QuestionnaireProject.SmsServiceIran.getgroupmobilesRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getgroupmobilesRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            return ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getgroupmobilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestionnaireProject.SmsServiceIran.getgroupmobilesstrResponse QuestionnaireProject.SmsServiceIran.ServiceSoap.getgroupmobilesstr(QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequest request) {
            return base.Channel.getgroupmobilesstr(request);
        }
        
        public string getgroupmobilesstr(string groupid, string appcode) {
            QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequest inValue = new QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            QuestionnaireProject.SmsServiceIran.getgroupmobilesstrResponse retVal = ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getgroupmobilesstr(inValue);
            return retVal.Body.getgroupmobilesstrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupmobilesstrResponse> QuestionnaireProject.SmsServiceIran.ServiceSoap.getgroupmobilesstrAsync(QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequest request) {
            return base.Channel.getgroupmobilesstrAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupmobilesstrResponse> getgroupmobilesstrAsync(string groupid, string appcode) {
            QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequest inValue = new QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getgroupmobilesstrRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            return ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getgroupmobilesstrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestionnaireProject.SmsServiceIran.getgroupcountResponse QuestionnaireProject.SmsServiceIran.ServiceSoap.getgroupcount(QuestionnaireProject.SmsServiceIran.getgroupcountRequest request) {
            return base.Channel.getgroupcount(request);
        }
        
        public string getgroupcount(string groupid, string appcode) {
            QuestionnaireProject.SmsServiceIran.getgroupcountRequest inValue = new QuestionnaireProject.SmsServiceIran.getgroupcountRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getgroupcountRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            QuestionnaireProject.SmsServiceIran.getgroupcountResponse retVal = ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getgroupcount(inValue);
            return retVal.Body.getgroupcountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupcountResponse> QuestionnaireProject.SmsServiceIran.ServiceSoap.getgroupcountAsync(QuestionnaireProject.SmsServiceIran.getgroupcountRequest request) {
            return base.Channel.getgroupcountAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getgroupcountResponse> getgroupcountAsync(string groupid, string appcode) {
            QuestionnaireProject.SmsServiceIran.getgroupcountRequest inValue = new QuestionnaireProject.SmsServiceIran.getgroupcountRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getgroupcountRequestBody();
            inValue.Body.groupid = groupid;
            inValue.Body.appcode = appcode;
            return ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getgroupcountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestionnaireProject.SmsServiceIran.SendSMSResponse QuestionnaireProject.SmsServiceIran.ServiceSoap.SendSMS(QuestionnaireProject.SmsServiceIran.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(string username, string password, string text, string mobileno, string pnlno) {
            QuestionnaireProject.SmsServiceIran.SendSMSRequest inValue = new QuestionnaireProject.SmsServiceIran.SendSMSRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.SendSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            inValue.Body.pnlno = pnlno;
            QuestionnaireProject.SmsServiceIran.SendSMSResponse retVal = ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.SendSMSResponse> QuestionnaireProject.SmsServiceIran.ServiceSoap.SendSMSAsync(QuestionnaireProject.SmsServiceIran.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.SendSMSResponse> SendSMSAsync(string username, string password, string text, string mobileno, string pnlno) {
            QuestionnaireProject.SmsServiceIran.SendSMSRequest inValue = new QuestionnaireProject.SmsServiceIran.SendSMSRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.SendSMSRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            inValue.Body.pnlno = pnlno;
            return ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestionnaireProject.SmsServiceIran.RemainSmsResponse QuestionnaireProject.SmsServiceIran.ServiceSoap.RemainSms(QuestionnaireProject.SmsServiceIran.RemainSmsRequest request) {
            return base.Channel.RemainSms(request);
        }
        
        public string RemainSms(string username, string password) {
            QuestionnaireProject.SmsServiceIran.RemainSmsRequest inValue = new QuestionnaireProject.SmsServiceIran.RemainSmsRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.RemainSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            QuestionnaireProject.SmsServiceIran.RemainSmsResponse retVal = ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).RemainSms(inValue);
            return retVal.Body.RemainSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.RemainSmsResponse> QuestionnaireProject.SmsServiceIran.ServiceSoap.RemainSmsAsync(QuestionnaireProject.SmsServiceIran.RemainSmsRequest request) {
            return base.Channel.RemainSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.RemainSmsResponse> RemainSmsAsync(string username, string password) {
            QuestionnaireProject.SmsServiceIran.RemainSmsRequest inValue = new QuestionnaireProject.SmsServiceIran.RemainSmsRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.RemainSmsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).RemainSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestionnaireProject.SmsServiceIran.Send1smsResponse QuestionnaireProject.SmsServiceIran.ServiceSoap.Send1sms(QuestionnaireProject.SmsServiceIran.Send1smsRequest request) {
            return base.Channel.Send1sms(request);
        }
        
        public string Send1sms(string username, string text, string mobileno) {
            QuestionnaireProject.SmsServiceIran.Send1smsRequest inValue = new QuestionnaireProject.SmsServiceIran.Send1smsRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.Send1smsRequestBody();
            inValue.Body.username = username;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            QuestionnaireProject.SmsServiceIran.Send1smsResponse retVal = ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).Send1sms(inValue);
            return retVal.Body.Send1smsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.Send1smsResponse> QuestionnaireProject.SmsServiceIran.ServiceSoap.Send1smsAsync(QuestionnaireProject.SmsServiceIran.Send1smsRequest request) {
            return base.Channel.Send1smsAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.Send1smsResponse> Send1smsAsync(string username, string text, string mobileno) {
            QuestionnaireProject.SmsServiceIran.Send1smsRequest inValue = new QuestionnaireProject.SmsServiceIran.Send1smsRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.Send1smsRequestBody();
            inValue.Body.username = username;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            return ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).Send1smsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestionnaireProject.SmsServiceIran.Send1BulkResponse QuestionnaireProject.SmsServiceIran.ServiceSoap.Send1Bulk(QuestionnaireProject.SmsServiceIran.Send1BulkRequest request) {
            return base.Channel.Send1Bulk(request);
        }
        
        public string Send1Bulk(string username, string text, string mobileno) {
            QuestionnaireProject.SmsServiceIran.Send1BulkRequest inValue = new QuestionnaireProject.SmsServiceIran.Send1BulkRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.Send1BulkRequestBody();
            inValue.Body.username = username;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            QuestionnaireProject.SmsServiceIran.Send1BulkResponse retVal = ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).Send1Bulk(inValue);
            return retVal.Body.Send1BulkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.Send1BulkResponse> QuestionnaireProject.SmsServiceIran.ServiceSoap.Send1BulkAsync(QuestionnaireProject.SmsServiceIran.Send1BulkRequest request) {
            return base.Channel.Send1BulkAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.Send1BulkResponse> Send1BulkAsync(string username, string text, string mobileno) {
            QuestionnaireProject.SmsServiceIran.Send1BulkRequest inValue = new QuestionnaireProject.SmsServiceIran.Send1BulkRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.Send1BulkRequestBody();
            inValue.Body.username = username;
            inValue.Body.text = text;
            inValue.Body.mobileno = mobileno;
            return ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).Send1BulkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QuestionnaireProject.SmsServiceIran.getcitymobilesResponse QuestionnaireProject.SmsServiceIran.ServiceSoap.getcitymobiles(QuestionnaireProject.SmsServiceIran.getcitymobilesRequest request) {
            return base.Channel.getcitymobiles(request);
        }
        
        public string getcitymobiles(string cityid, int mode) {
            QuestionnaireProject.SmsServiceIran.getcitymobilesRequest inValue = new QuestionnaireProject.SmsServiceIran.getcitymobilesRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getcitymobilesRequestBody();
            inValue.Body.cityid = cityid;
            inValue.Body.mode = mode;
            QuestionnaireProject.SmsServiceIran.getcitymobilesResponse retVal = ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getcitymobiles(inValue);
            return retVal.Body.getcitymobilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getcitymobilesResponse> QuestionnaireProject.SmsServiceIran.ServiceSoap.getcitymobilesAsync(QuestionnaireProject.SmsServiceIran.getcitymobilesRequest request) {
            return base.Channel.getcitymobilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<QuestionnaireProject.SmsServiceIran.getcitymobilesResponse> getcitymobilesAsync(string cityid, int mode) {
            QuestionnaireProject.SmsServiceIran.getcitymobilesRequest inValue = new QuestionnaireProject.SmsServiceIran.getcitymobilesRequest();
            inValue.Body = new QuestionnaireProject.SmsServiceIran.getcitymobilesRequestBody();
            inValue.Body.cityid = cityid;
            inValue.Body.mode = mode;
            return ((QuestionnaireProject.SmsServiceIran.ServiceSoap)(this)).getcitymobilesAsync(inValue);
        }
    }
}
